language: go
go:
- 1.12.x
cache:
  directories:
    - $GOPATH/pkg/mod
env:
  global:
    - GO111MODULE=on
    - RELEASE=
before_install:
- go get -u github.com/axw/gocov/gocov
- go get golang.org/x/tools/cmd/cover
- go get github.com/mitchellh/gox
script:
- make build
- make test
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: bin/*
  draft: true
  overwrite: true
  on:
    tags: true
  api_key:
    secure: X6+wzqhCdDeax0sFeXuFSf0qB/b8diOAfEIasLf/srNp0V4gJQJxRm8llxvio6597hwH8tvtiHLr7yjOXpi8ASskojilIM0+9TmIgqOVV1q+dgEz9Tk83/qJ457UqS9Ako48v2NNbd4z+AGXOomElXNQND7g8cijw3h13vWHGQrm2xWp61Y/bjAUbRLS/8Co7htSPMmc6oikjiEKCbYj8PuwXKRVfE1Fv+jSejhZD2vuMbJEpaqPqhEiZp3mUlgBlAFrL1LWr3p9w8T3yPOm0r07S8GOOK3j9bQIJdUv+Qi6GuGkG5jzXk5cXAx2L+iI6nQoTU9L7xkDyqQiV4OCVI9bH/WRUYXOZeIveWHSsA46RhKbmH8WW5D1LkMUVJpYQddgW34Sw31funvCDDxjAmKMXbMxU5mdc52O7HiRio4uh6twI5gz4GXZ6uAuAve2ulqevvKmV8Wq0/a1SaDZl+yIg2dT0iCgqI9hkdnFpvZFojpDa8Io7oOw7oTLwV0+3B2JLJd2BYJ3LS5ldGkou/DhYNX3noL+P+aBicidhqPDSMs+OIo4cjjDS5/+OLbj1Lqigeveq+3aXe3dLJjq4RL7GXLnL/4y/n+ztW57qSQK3V+S+fYHNwDskpLQYEALliO2NoXrKtiKIP6YmdpGhPtGSAyT4kg+9cfCmPYyzk8=
