ConfigKey:
  type: string
  description: |
    ID of specific configuration field. The ID must point to an existing
    leaf field.  For example, with a configuration:

    ```
    daemon:
      interval: 3600

    proxy: direct
    ```

    IDs `daemon.interval`, `proxy` are acceptable, but IDs `daemon` or
    `proxy.ip` are not acceptable.

  examples:
    "top level field": proxy
    "nested field": daemon.interval

ErrorInfo:
  type: object
  properties:
    msg:
      type: string
      description: reason of error
      example:
        msg: "'daemon' is not a leaf field"
